myadmin/urls.py
from django.urls import path, re_path
from . import views

urlpatterns = [
    # Common
    re_path(r'^$', views.index, name='myadmin_index'),
    re_path(r'^login$', views.login, name='myadmin_login'),
    # Danh muc 
    re_path(r'^danhmuc$', views.danhmuc, name='danhmuc_index'),
    re_path(r'^danhmuc_tao$', views.danhmuc_tao, name='danhmuc_tao'),
    re_path(r'^danhmuc_sua/(?P<danhmuc_id>[0-9]+)$', views.danhmuc_sua, name='danhmuc_sua'),
    re_path(r'^danhmuc_xoa/(?P<danhmuc_id>[0-9]+)$', views.danhmuc_xoa, name='danhmuc_xoa'),
    # Bai viet 
    re_path(r'^baiviet$', views.baiviet_index, name='baiviet_index'),
    re_path(r'^baiviet_tao$', views.baiviet_tao, name='baiviet_tao'),
    re_path(r'^baiviet_sua/(?P<baiviet_id>[0-9]+)$', views.baiviet_sua, name='baiviet_sua'),
    re_path(r'^baiviet_xoa/(?P<baiviet_id>[0-9]+)$', views.baiviet_xoa, name='baiviet_xoa'),

    # url(r'^export_order_wo_doc/$', fixbug.export_order_wo_doc, name='weekly_enterpriseorder_report'),
]

phongthuy_thanhnhan/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from . import views
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth.decorators import user_passes_test

urlpatterns = [
    path('summernote/', include('django_summernote.urls')),
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    re_path(r'^tintuc/', include('tintuc.urls')),
    re_path(r'^myadmin/', include('myadmin.urls')),
    
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

tutru/urls.py
from django.urls import include, path
from . import views

urlpatterns = [
    # … other patterns
    path('', views.index, name='turu'),
    # … other patterns
]

myadmin/models.py
from django.db import models
from django.contrib.auth.models import User

class danhsachtintuc(models.Model):
    ten = models.CharField(max_length=255, null=True, blank=True) 
    mieuta = models.CharField(max_length=4096, null=True, blank=True) 
    trangthai = models.BooleanField(default=True, blank=True)
    ngaytao = models.DateTimeField(null=True, blank=True)


class baiviet(models.Model):
    danhsachtintuc = models.ForeignKey(danhsachtintuc, related_name='dmtt', on_delete=models.SET_NULL, null=True, blank=True)
    ten = models.CharField(max_length=255, null=True, blank=True) 
    hinhanh = models.CharField(max_length=255, null=True, blank=True)
    mieuta = models.CharField(max_length=4096, null=True, blank=True) 
    noidung = models.CharField(max_length=20096, null=True, blank=True) 
    trangthai = models.BooleanField(default=True, blank=True)
    ngaytao = models.DateTimeField(null=True, blank=True)    
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)

myadmin/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.core.validators import validate_email
from django.forms import ModelForm
from myadmin.models import *
from django.forms import ModelChoiceField
from django_summernote.widgets import SummernoteWidget, SummernoteInplaceWidget

class NameChoiceField(ModelChoiceField):
    def label_from_instance(self, obj):
        return f'{obj.ten}'

class danhsachtintuc_form(ModelForm):
    ten = forms.CharField(max_length=255, widget=forms.TextInput(), required=True)
    mieuta = forms.CharField(max_length=4096, widget=forms.Textarea({'rows':'3', 'style': 'width:100%;'}), required=True)
    class Meta:
        model = danhsachtintuc
        fields = '__all__'
        exclude = []
        widgets = {
            'ten': forms.TextInput(attrs={'style': 'width:100%;'}),
            'mieuta': forms.Textarea(attrs={'rows':'3', 'style': 'width:100%;'}),
        }

    def __init__(self, *args, **kwargs):
        super(danhsachtintuc_form, self).__init__(*args, **kwargs)
        CONTAINER_STATUS_CHOICES = (
            ("1", "Hoạt Động"),
            ("0", "Không Hoạt Động")
        )
        self.fields['trangthai'] = forms.ChoiceField(choices=CONTAINER_STATUS_CHOICES, widget=forms.Select(attrs={}))
        
class baiviet_form(ModelForm):
    danhsachtintuc = NameChoiceField(queryset=danhsachtintuc.objects.filter(trangthai=True), required=True)
    ten = forms.CharField(max_length=255, widget=forms.TextInput(), required=True)
    hinhanh = forms.FileField(required=False)
    mieuta = forms.CharField(max_length=4096, widget=forms.Textarea({'rows':'3', 'style': 'width:100%;'}), required=False)
    noidung = forms.CharField(widget=SummernoteWidget())
    class Meta:
        model = baiviet
        fields = '__all__'
        exclude = []
        widgets = {
            'ten': forms.TextInput(attrs={'style': 'width:100%;', 'required':'true'}),
            'mieuta': forms.Textarea(attrs={'rows':'3', 'style': 'width:100%;'}),
        }

    def __init__(self, *args, **kwargs):
        super(baiviet_form, self).__init__(*args, **kwargs)
        CONTAINER_STATUS_CHOICES = (
            ("1", "Hoạt Động"),
            ("0", "Không Hoạt Động")
        )
        self.fields['trangthai'] = forms.ChoiceField(choices=CONTAINER_STATUS_CHOICES, widget=forms.Select(attrs={}))

myadmin/views.py
import os
from datetime import datetime
from django.shortcuts import render
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse, HttpResponseRedirect
from rest_framework import status
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login
from phongthuy_thanhnhan.funcs import *
from myadmin.forms import *
from django.conf import settings

def index(request):
    # check had logged
    print('danhmuc==========')
    if check_login(request):
        return render(request,"myadmin/index.html")
    else:
        return HttpResponseRedirect("/myadmin/login")

def login(request):
    print('login')
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            print('user==========',user)
            if user.is_active:        
                obj_json = {
                    "success": True
                }
                print('user is_active==========',user.is_active)
                request.session['admin'] = 'admin'
                return HttpResponseRedirect("/myadmin")
            else:
                return render(request,"myadmin/login.html", {"status":False})
        else:
            return render(request,"myadmin/login.html", {"status":False})

    return render(request,"myadmin/login.html")

# ============================ Danh Muc ==============================
def danhmuc(request):
    print('danhmuc')
    # check had logged
    if check_login(request):
        danhmuc_list = danhsachtintuc.objects.all().order_by('-trangthai','ngaytao')
        return render(request,"myadmin/danhmuc.html",{"danhmuc_list":danhmuc_list})
    else:
        return HttpResponseRedirect("/myadmin/login")

def danhmuc_tao(request):
    print('danhmuc tao')
    # check had logged
    if check_login(request):
        if request.method == "POST":
            mform = danhsachtintuc_form(request.POST)
            if mform.is_valid():
                new_model = mform.save(commit=False)
                new_model.ngaytao = datetime.now()                
                status = True
                if str(request.POST['trangthai']) == '0':
                    status = False                 
                new_model.trangthai = status
                new_model.save()
                return HttpResponseRedirect("/myadmin/danhmuc")
            else:
                print(mform.errors)
        else:
            dm_form = danhsachtintuc_form(instance=danhsachtintuc())
            return render(request,"myadmin/danhmuc_tao.html", {"dm_form":dm_form})
    else:
        return HttpResponseRedirect("/myadmin/login")

def danhmuc_sua(request, danhmuc_id):
    print('danhmuc sua')
    # check had logged
    if check_login(request):
        obj_model = danhsachtintuc.objects.get(id=danhmuc_id)
        if request.method == "POST":
            mform = danhsachtintuc_form(request.POST or None, instance=obj_model)
            if mform.is_valid():
                obj_model.ten =  request.POST['ten']
                obj_model.mieuta =  request.POST['mieuta']               
                status = True
                if str(request.POST['trangthai']) == '0':
                    status = False                 
                obj_model.trangthai = status
                obj_model.save()
                return HttpResponseRedirect("/myadmin/danhmuc")
            else:
                print(mform.errors)
        else:
            dm_form = danhsachtintuc_form(instance=obj_model)
            return render(request,"myadmin/danhmuc_sua.html", {"dm_form":dm_form,"danhmuc_id":danhmuc_id,"obj_model":obj_model})
    else:
        return HttpResponseRedirect("/myadmin/login")

def danhmuc_xoa(request, danhmuc_id):
    print('danhmuc xoa')
    # check had logged
    if check_login(request):
        try:
            obj_model = danhsachtintuc.objects.get(id=danhmuc_id)
            obj_model.trangthai = False
            obj_model.save()
        except:
            pass
        return HttpResponseRedirect("/myadmin/danhmuc")
    else:
        return HttpResponseRedirect("/myadmin/login")
    
# ============================ Bai Viet ==============================
def baiviet_index(request):
    print('baiviet')
    # check had logged
    if check_login(request):
        baiviet_list = baiviet.objects.all().order_by('-trangthai','ngaytao')
        return render(request,"myadmin/baiviet.html",{"baiviet_list":baiviet_list})
    else:
        return HttpResponseRedirect("/myadmin/login")

def baiviet_tao(request):
    print('baiviet tao')
    # check had logged
    if check_login(request):
        if request.method == "POST":
            mform = baiviet_form(request.POST)
            if mform.is_valid():
                fpath = ''
                if request.FILES:                  
                    filesize=0
                    for f in request.FILES.getlist('hinhanh'):
                        filesize=filesize+ f.size
                    if filesize <  10000000:
                        for f in request.FILES.getlist('hinhanh'):
                            curr_dt = datetime.now()
                            timestamp = str(round(curr_dt.timestamp()))
                            filename = timestamp+'_'+f.name
                            mediaPtah = os.path.join(settings.MEDIA_ROOT,'news')
                            fpath = os.path.join(mediaPtah, filename)
                            open(fpath, 'wb').write(f.file.read())
                new_model = mform.save(commit=False)
                new_model.ngaytao = datetime.now()                
                status = True
                if str(request.POST['trangthai']) == '0':
                    status = False    
                new_model.hinhanh = fpath             
                new_model.trangthai = status
                new_model.save()
                return HttpResponseRedirect("/myadmin/baiviet")
            else:
                print(mform.errors)
        else:
            dm_form = baiviet_form(instance=baiviet())
            return render(request,"myadmin/baiviet_tao.html", {"dm_form":dm_form})
    else:
        return HttpResponseRedirect("/myadmin/login")

def baiviet_sua(request, baiviet_id):
    print('baiviet sua')
    # check had logged
    if check_login(request):
        obj_model = baiviet.objects.get(id=baiviet_id)
        if request.method == "POST":
            mform = baiviet_form(request.POST or None, instance=obj_model)
            if mform.is_valid():
                fpath = ''
                if request.FILES:                  
                    filesize=0
                    for f in request.FILES.getlist('hinhanh'):
                        filesize=filesize+ f.size
                    if filesize <  10000000:
                        for f in request.FILES.getlist('hinhanh'):
                            curr_dt = datetime.now()
                            timestamp = str(round(curr_dt.timestamp()))
                            filename = timestamp+'_'+f.name
                            fpath = os.path.join(settings.MEDIA_ROOT + '/news/', filename)
                            open(fpath, 'wb').write(f.file.read())
                obj_model.ten =  request.POST['ten']                
                obj_model.hinhanh = fpath
                obj_model.mieuta =  request.POST['mieuta']   
                obj_model.noidung =  request.POST['noidung']             
                status = True
                if str(request.POST['trangthai']) == '0':
                    status = False                 
                obj_model.trangthai = status
                obj_model.save()
                return HttpResponseRedirect("/myadmin/baiviet")
            else:
                print(mform.errors)
        else:
            dm_form = baiviet_form(instance=obj_model)
            return render(request,"myadmin/baiviet_sua.html", {"dm_form":dm_form,"baiviet_id":baiviet_id,"obj_model":obj_model})
    else:
        return HttpResponseRedirect("/myadmin/login")

def baiviet_xoa(request, baiviet_id):
    print('baiviet xoa')
    # check had logged
    if check_login(request):
        try:
            obj_model = baiviet.objects.get(id=baiviet_id)
            obj_model.trangthai = False
            obj_model.save()
        except:
            pass
        return HttpResponseRedirect("/myadmin/baiviet")
    else:
        return HttpResponseRedirect("/myadmin/login")

myadmin/templates/myadmin/baiviet.html
{% extends 'myadmin_base.html' %}
{% load static %}
{% load custom_templatetag %}
{% block content %}
<!-- Content Start -->
<div class="container-xxl py-4 pt-5">
  <div class="row g-4">
    <div class="col-sm-12">
      <!-- Bat Tu Start -->
      <div class="col-sm-12 pb-5">
          <div class="col-12 pb-3" style="min-height:500px">
              <div class="col-12">
                  <h2>Bài Viết</h2>
              </div>
              <div class="col-12 text-end">
                  <a class="btn btn-primary" href="/myadmin/baiviet_tao">Tạo Mới</a>
              </div>
              <div class="col-12 py-4">
                  <table class="tbl">
                    <thead>
                      <th>Tên Danh Mục</th>
                      <th>Tên Bài Viết</th>
                      <th>Mô Tả</th>
                      <th>Ngày Tạo</th>
                      <th>Hình Đại Diện</th>
                      <th>Trạng Thái</th>
                      <th></th>
                    </thead>
                    <tbody>
                      {% for obj in baiviet_list %}
                        <tr>
                          <td class="fw-bold">{{obj.ten}}</td>
                          <td>{{obj.danhsachtintuc.ten}}</td>
                          <td>{{obj.mieuta}}</td>
                          <td>{{obj.ngaytao|date:"d-m-Y"}}</td>
                          <td><img src="{{obj.hinhanh|img_path_remove_code}}" alt="" width="70"/></td>
                          <td>
                            {% if obj.trangthai %}
                              Hoạt động
                            {% else %}
                              Không hoạt động
                            {% endif %}
                          </td>
                          <td class="fw-bold"><a href="/myadmin/baiviet_sua/{{obj.id}}">Sửa</a> | 
                            <a href="javascript:void(0)" onclick="del('{{obj.id}}')">Xóa</a></td>
                        </tr>
                      {% endfor %}
                    </tbody>
                  </table>
              </div>
          </div>
      </div>
      <!-- Bat Tu End -->
    </div>
  </div>
</div>
<!-- Content End -->

<script>
  function del(id){
    if (confirm('Bạn chắc chắn muốn xóa?')) {
        location.href='/myadmin/baiviet_xoa/'+id;
    }
    else {
        return false;
    }
  }
</script>
{% endblock%}

myadmin/templates/myadmin/baiviet_sua.html
{% extends 'myadmin_base.html' %}
{% load static %}
{% load custom_templatetag %}
{% block content %}
<!-- Content Start -->
<div class="container-xxl py-4 pt-5">
  <div class="row g-4">
    <div class="col-sm-12">
      <!-- Bat Tu Start -->
      <div class="col-sm-12 pb-5">
          <div class="col-12 pb-3" style="min-height:500px">
              <div class="col-12">
                  <h2>Danh Mục Bài Viết</h2>
              </div>
              <div class="col-12 py-4">
                <form role="form" method="post" enctype="multipart/form-data" action="/myadmin/baiviet_tao" name="form" id="form">
                  
                  <div class="row">
                    Danh mục tin tức
                    {{ dm_form.danhsachtintuc }}
                    {{ dm_form.danhsachtintuc.errors }}
                  </div>
                  <div class="row">
                    Tiêu đề
                    {{ dm_form.ten }}
                    {{ dm_form.ten.errors }}
                  </div>
                  <div class="row py-1">
                    <table>
                      <tr>
                        <td>                          
                          Hình ảnh (Kích cở ngang x cao: 850 x 450 px)<br/>
                          {{ dm_form.hinhanh }}
                          {{ dm_form.hinhanh.errors }}
                        </td>
                        <td>
                          <img src="{{obj_model.hinhanh|img_path_remove_code}}" alt="" style="max-width: 200px;"/>
                        </td>
                      </tr>
                    </table>

                  </div>
                  <div class="row py-1">
                    Miêu tả
                    {{ dm_form.mieuta }}
                    {{ dm_form.mieuta.errors }}
                  </div>
                  <div class="row py-1">
                    Nội dung
                    {{ dm_form.noidung }}
                    {{ dm_form.noidung.errors }}
                  </div>
                  <div class="row py-1">
                    Trạng thái
                    {{ dm_form.trangthai }}
                    {{ dm_form.trangthai.errors }}
                  </div>
                  <div class="py-3 text-end">
                    <button type="submit" class="btn btn-primary">Cập Nhật</button>
                    <a class="btn btn-secondary" href="/myadmin/danhmuc">Trở Lại</a>
                  </div>
                  {% csrf_token %}
                </form>
              </div>
          </div>
      </div>
      <!-- Bat Tu End -->
    </div>
  </div>
</div>
<!-- Content End -->

{% endblock%}

myadmin/templates/myadmin/baiviet_tao.html
{% extends 'myadmin_base.html' %}
{% load static %}
{% block content %}
<!-- Content Start -->
<div class="container-xxl py-4 pt-5">
  <div class="row g-4">
    <div class="col-sm-12">
      <!-- Bat Tu Start -->
      <div class="col-sm-12 pb-5">
          <div class="col-12 pb-3" style="min-height:500px">
              <div class="col-12">
                  <h2>Danh Mục Bài Viết</h2>
              </div>
              <div class="col-12 py-4">
                <form role="form" method="post" enctype="multipart/form-data" action="/myadmin/baiviet_tao" name="form" id="form">
                  
                  <div class="row">
                    Danh mục tin tức
                    {{ dm_form.danhsachtintuc }}
                    {{ dm_form.danhsachtintuc.errors }}
                  </div>
                  <div class="row">
                    Tiêu đề
                    {{ dm_form.ten }}
                    {{ dm_form.ten.errors }}
                  </div>
                  <div class="row">
                    Hình ảnh (Kích cở ngang x cao: 850 x 450 px)
                    {{ dm_form.hinhanh }}
                    {{ dm_form.hinhanh.errors }}
                  </div>
                  <div class="row py-1">
                    Miêu tả
                    {{ dm_form.mieuta }}
                    {{ dm_form.mieuta.errors }}
                  </div>
                  <div class="row py-1">
                    Nội dung
                    {{ dm_form.noidung }}
                    {{ dm_form.noidung.errors }}
                  </div>
                  <div class="row py-1">
                    Trạng thái
                    {{ dm_form.trangthai }}
                    {{ dm_form.trangthai.errors }}
                  </div>
                  <div class="py-3 text-end">
                    <button type="submit" class="btn btn-primary">Tạo Mới</button>
                    <a class="btn btn-secondary" href="/myadmin/danhmuc">Trở Lại</a>
                  </div>
                  {% csrf_token %}
                </form>
              </div>
          </div>
      </div>
      <!-- Bat Tu End -->
    </div>
  </div>
</div>
<!-- Content End -->

{% endblock%}

myadmin/templates/myadmin/danhmuc.html
{% extends 'myadmin_base.html' %}
{% load static %}
{% block content %}
<!-- Content Start -->
<div class="container-xxl py-4 pt-5">
  <div class="row g-4">
    <div class="col-sm-12">
      <!-- Bat Tu Start -->
      <div class="col-sm-12 pb-5">
          <div class="col-12 pb-3" style="min-height:500px">
              <div class="col-12">
                  <h2>Danh Mục Bài Viết</h2>
              </div>
          </div>
      </div>
      <!-- Bat Tu End -->
    </div>
  </div>
</div>
<!-- Content End -->
{% endblock%}

myadmin/templates/myadmin/danhmuc_sua.html
{% extends 'myadmin_base.html' %}
{% load static %}
{% block content %}
<!-- Content Start -->
<div class="container-xxl py-4 pt-5">
  <div class="row g-4">
    <div class="col-sm-12">
      <!-- Bat Tu Start -->
      <div class="col-sm-12 pb-5">
          <div class="col-12 pb-3" style="min-height:500px">
              <div class="col-12">
                  <h2>Danh Mục Bài Viết</h2>
              </div>
              <div class="col-12 py-4">
                <form method="POST" action="/myadmin/danhmuc_sua/{{danhmuc_id}}" name="form">
                  {% csrf_token %}
                  <div class="row">
                    Tên Danh mục
                    {{ dm_form.ten }}
                    {{ dm_form.ten.errors }}
                  </div>
                  <div class="row py-1">
                    Miêu tả
                    {{ dm_form.mieuta }}
                    {{ dm_form.mieuta.errors }}
                  </div>
                  <div class="row py-1">
                    Trạng thái
                    {{ dm_form.trangthai }}
                    {{ dm_form.trangthai.errors }}
                  </div>
                  <div class="py-3 text-end">
                    <button type="submit" class="btn btn-primary">Cập Nhật</button>
                    <a class="btn btn-secondary" href="/myadmin/danhmuc">Trở Lại</a>
                  </div>
                </form>
              </div>
          </div>
      </div>
      <!-- Bat Tu End -->
    </div>
  </div>
</div>
<!-- Content End -->

<script>
   $(document).ready(function () {
    // set status which selected
    var status = '{{obj_model.trangthai}}';
    if(status == 'True'){
      status = '1';
    }
    else{
      status = '0';
    }
    $('#id_trangthai').val(status);
   });
</script>
{% endblock%}

myadmin/templates/myadmin/danhmuc_tao.html
{% extends 'myadmin_base.html' %}
{% load static %}
{% block content %}
<!-- Content Start -->
<div class="container-xxl py-4 pt-5">
  <div class="row g-4">
    <div class="col-sm-12">
      <!-- Bat Tu Start -->
      <div class="col-sm-12 pb-5">
          <div class="col-12 pb-3" style="min-height:500px">
              <div class="col-12">
                  <h2>Bài Viết</h2>
              </div>
              <div class="col-12 py-4">
                <form method="POST" action="/myadmin/baiviet_tao" name="form">
                  {% csrf_token %}
                  <div class="row">
                    Tên Danh mục
                    {{ dm_form.ten }}
                    {{ dm_form.ten.errors }}
                  </div>
                  <div class="row py-1">
                    Miêu tả
                    {{ dm_form.mieuta }}
                    {{ dm_form.mieuta.errors }}
                  </div>
                  <div class="row py-1">
                    Trạng thái
                    {{ dm_form.trangthai }}
                    {{ dm_form.trangthai.errors }}
                  </div>
                  <div class="py-3 text-end">
                    <button type="submit" class="btn btn-primary">Tạo Mới</button>
                    <a class="btn btn-secondary" href="/myadmin/baiviet">Trở Lại</a>
                  </div>
                </form>
              </div>
          </div>
      </div>
      <!-- Bat Tu End -->
    </div>
  </div>
</div>
<!-- Content End -->
{% endblock%}

myadmin/templates/myadmin/danhmuc_xoa.html
{% extends 'myadmin_base.html' %}
{% load static %}
{% block content %}
<!-- Content Start -->
<div class="container-xxl py-4 pt-5">
  <div class="row g-4">
    <div class="col-sm-12">
      <!-- Bat Tu Start -->
      <div class="col-sm-12 pb-5">
          <div class="col-12 pb-3" style="min-height:500px">
              <div class="col-12">
                  <h2>Danh Mục Bài Viết</h2>
              </div>
              <div class="col-12 py-4">
                <form method="POST" action="/myadmin/danhmuc_sua/{{danhmuc_id}}" name="form">
                  {% csrf_token %}
                  <div class="row">
                    Tên Danh mục
                    {{ dm_form.ten }}
                    {{ dm_form.ten.errors }}
                  </div>
                  <div class="row py-1">
                    Miêu tả
                    {{ dm_form.mieuta }}
                    {{ dm_form.mieuta.errors }}
                  </div>
                  <div class="row py-1">
                    Trangj thái
                    {{ dm_form.trangthai }}
                    {{ dm_form.trangthai.errors }}
                  </div>
                  <div class="py-3 text-end">
                    <button type="submit" class="btn btn-primary">Cập Nhật</button>
                    <a class="btn btn-secondary" href="/myadmin/danhmuc">Trở Lại</a>
                  </div>
                </form>
              </div>
          </div>
      </div>
      <!-- Bat Tu End -->
    </div>
  </div>
</div>
<!-- Content End -->

<script>
   $(document).ready(function () {
    // set status which selected
    var status = '{{obj_model.trangthai}}';
    if(status == 'True'){
      status = '1';
    }
    else{
      status = '0';
    }
    $('#id_trangthai').val(status);
   });
</script>
{% endblock%}

myadmin/templates/myadmin/index.html
{% extends 'myadmin_base.html' %}
{% load static %}
{% block content %}
<!-- Content Start -->
<div class="container-xxl py-4 pt-5">
  <div class="row g-4">
    <div class="col-sm-12">
      <!-- Bat Tu Start -->
      <div class="col-sm-12 pb-5">
          <div class="col-12 pb-3" style="min-height:500px">
              <div class="col-12">
                  <h2>CHÀO MỪNG</h2>
              </div>
          </div>
      </div>
      <!-- Bat Tu End -->
    </div>
  </div>
</div>
<!-- Content End -->
{% endblock%}

myadmin/templates/myadmin/login.html
{% extends 'myadmin_login_base.html' %}
{% load static %}
{% block content %}
<!-- Content Start -->
<div class="container-xxl py-4 pt-5">
  <div class="row g-4">
    <div class="col-sm-12">
      <!-- Bat Tu Start -->
      <div class="col-sm-12 pb-5">
          <div class="col-12 pb-3 d-flex align-items-center justify-content-center">
              <div class="col-6  text-center">
                  <h2>Đăng Nhập</h2>
                  <form method="POST" action="" name="login" enctype="multipart/form-data" name="change-form">
                    {% csrf_token %}
                    <div class="row g-3">
                      <div class="col-12 col-sm-12">
                          <input type="text" id="username" name="username" class="form-control" placeholder="Tài khoản" required="true">
                      </div>
                      <div class="col-12 col-sm-12">
                          <input type="password" id="password" name="password" class="form-control" placeholder="Mật khẩu" required="true">
                      </div>                      
                      <div class="col-12 text-center">
                        <button class="btn btn-primary py-3 px-5" type="submit">Đăng Nhập</button>
                      </div>                      
                      <div class="col-12 text-center text-danger fw-bold jsalert">
                        
                      </div>
                    </div>
                  </form>
              </div>
          </div>
      </div>
      <!-- Bat Tu End -->
    </div>
  </div>
</div>
<!-- Content End -->

<script>
  status = '{{status}}';
  if(status == 'False'){
    $('.jsalert').html('Tài Khoản hoặc Mật Khẩu không đúng.')
  }
  $("form[name=login]").on('submit', function(e) {
    $.ajax({
      url: '/myadmin/login',
      data: new FormData(this),
      type: 'POST',
      cache: false,
      contentType: false,
      processData: false,
      success: function(data) {
         // no action 
      },
      error: function() {
          alert('An error has occurred');
      }
    });
  });
</script>
{% endblock%}